config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'
  
  get '/dashboard', to: 'dashboard#index'

  devise_for :users

  resources :users, only: [:show]
  resources :invoices
  resources :clients

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :user
	has_many :invoices

	# Client validations
	validates :company_name, :first_name, :last_name, :address, presence: true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	belongs_to :user
	belongs_to :client
	has_many :items, dependent: :destroy
	accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

	# Invoice validations
	validates :name, :invoice_number, :currency, :subtotal, :total, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_many :clients
	has_many :invoices
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email,
    																									 :website, :address, :postal_code, :city,
    																									 :country, :phone, :company_logo, :company_name ])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:first_name, :last_name, :email,
    																									 :website, :address, :postal_code, :city,
    																									 :country, :phone, :company_logo, :company_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email,
    																									 :website, :address, :postal_code, :city,
    																									 :country, :phone, :company_logo, :company_name])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :set_client, only: [:show, :edit, :update, :delete]
  def index
  	@clients = Client.all
  end

  def new
  	@client = current_user.clients.build
  end

  def create
  	@client = current_user.clients.build(client_params)
  	if @client.save
      flash[:notice] = "Client succesfully created."
  		redirect_to clients_path
  	else
  		render 'new', notice:"something went wrong!"
  	end
  end

  def show 	
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to client_path(@client), notice: "Client details succesfully updated."
    else
      render 'edit', notice: "Something went wrong, please try again later."
    end
  end

  def delete
    @client.destroy
    redirect_to clients_path, notice: "Client succesfully deleted."
  end

  private

 		def client_params
 			params.require(:client).permit(:first_name, :last_name, :email, :website, :address, :postal_code,
 																		 :city, :country, :phone, :user_id, :invoice_id, :company_name)
 		end

 		def set_client
 			@client = Client.find(params[:id])
 		end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  	@user = current_user.id
  	@invoices = Invoice.all
  	@clients = Client.all
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index
		if user_signed_in?
			redirect_to dashboard_path
		end

		@index = true
	end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  require 'nokogiri'
  require 'open-uri'
	before_action :set_invoice, only: [:show, :destroy]
  before_action :invoice_due_list, only: [:new, :create]
	def index
		@user = current_user.id
		@invoices = Invoice.all
	end

  def new
  	@invoice = current_user.invoices.build
    xml_url = "https://www.currency-iso.org/dam/downloads/lists/list_one.xml"
    @currencies = Nokogiri::XML(open(xml_url))
  end

  def create
  	@invoice = current_user.invoices.build(invoice_params)
    xml_url = "https://www.currency-iso.org/dam/downloads/lists/list_one.xml"
    @currencies = Nokogiri::XML(open(xml_url))
    
  	if @invoice.save
      flash[:notice] = "Invoice succesfully created."
  		redirect_to invoices_path
  	else
  		render 'new', notice:"something went wrong!"
  	end
  end


  def show
    respond_to do |format|
      format.html
      format.pdf { render template: "invoices/invoice", pdf: "Invoice" }
    end
  end

  def destroy
    @invoice.destroy
    redirect_to invoices_path
  end

  private

 		def invoice_params
 			params.require(:invoice).permit(:name, :description, :invoice_number, :currency, :date, :invoice_due,
 																		 :tax, :invoice_note, :client_id, :subtotal, :total, 
                                     items_attributes: [:id, :name, :qty, :rate, :amount, :done, :_destroy])
 		end

 		def set_invoice
 			@invoice = Invoice.find(params[:id])
 		end

    def invoice_due_list
      @invoice_due_list = ["Due on Receipt", "After 7 days", "After 15 days",
                    "After 30 days", "After 45 days", "After 60 days"]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/clients/_form.html.haml
=simple_form_for @client do |f|
	=f.input :company_name, class:"form-control"
	=f.input :first_name, label: "Client First Name", class:"form-control"
	=f.input :last_name, label: "Client Last Name", class:"form-control"
	=f.input :email, label: "Client Email Address", class:"form-control"
	=f.input :website, label: "Client Website", class:"form-control"
	=f.input :address, class:"form-control"
	.form-inline
		.form-group
			=f.input :postal_code, class:"form-control"
			=f.input :city, class:"form-control"

			.dropdown.form-group	
				%label.control-label Country
				=f.country_select :country,{}, {class:"dropdown-toggle btn btn-default form-control", label:"Country"}
			-# =f.input :country, as: :string, class:"form-control"
	=f.input :phone, class:"form-control"
	=f.button :submit, class:"btn btn-success"
	=link_to "Cancel", clients_path, class:"btn btn-default"

app/views/clients/edit.html.haml
#wrapper
	#page-wrapper
		.row
			.col-lg-12
				.panel.panel-default
					.panel-heading
						%h2 Update Client Details
					.panel-body
						=render 'clients/form'

app/views/clients/index.html.haml
#wrapper
	#page-wrapper
		.row
			.col-lg-12
				.panel.panel-default
					.panel-heading
						%h2.clients-heading Clients section
						=link_to "New Client", new_client_path, class:"btn btn-success"
					.panel-body
						%table.table.table-striped.clients.table-hover
							%thead
								%tr
									%th Company Name
									%th Client Name
									%th Client Email
									%th Website
									%th Phone number
									%th Details
							%tbody
								-@clients.each do |client|
									%tr
										%td=client.company_name
										%td=client.first_name + " " + client.last_name
										%td=client.email
										%td=client.website
										%td=client.phone
										%td=link_to "Details", client_path(client), class:"btn btn-default btn-sm"

:javascript
	$(document).ready(function(){
		$('.clients').DataTable();
	});

app/views/clients/new.html.haml
#wrapper
	#page-wrapper
		.row
			.col-lg-12
				.panel.panel-default
					.panel-heading
						%h2 New Client
					.panel-body
						=render 'clients/form'

app/views/clients/show.html.haml
#wrapper
	#page-wrapper
		.row
			.col-lg-12
				.panel.panel-default
					.panel-heading
						%h2.clients-heading=@client.company_name
						=link_to "Delete Client", client_path(@client), method: :delete, data:{confirm:"Are you sure?"}, class:"btn btn-danger"
						=link_to "Edit Details", edit_client_path(@client), class:"btn btn-primary"
						=link_to "Back", clients_path, class:"btn btn-default"
					.panel-body
						%p
							.bold
								Company Name:
							=@client.company_name
						%p
							.bold
								Client Name:
							=@client.first_name + " " + @client.last_name
						%p
							.bold
								Email:
							=@client.email
						%p
							.bold
								Website:
							=@client.website
						%p
							.bold
								Phone number:
							=@client.phone
						%p
							.bold
								Address:
							=@client.address
						%p
							.bold
								Postal Code:
							=@client.postal_code
						%p
							.bold
								City:
							=@client.city
						%p
							.bold 
								Country:
							=@client.country
															

app/views/dashboard/_navigation.html.haml
-if user_signed_in?
	%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
		.navbar-header
			%button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			%a.navbar-brand{:href => "/"} 
				.fa.fa-grav.fa-2x
				InvoiceME
		%ul.nav.navbar-right.top-nav
			%li.dropdown
				%a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
					%i.fa.fa-bell
					Notifications
					%b.caret
				%ul.dropdown-menu
					%li
						%a{:href => "#"}
							%i.fa.fa-fw.fa-user
							Notification #1
					%li
						%a{:href => "#"}
							%i.fa.fa-fw.fa-envelope
							Notification #2
					%li
						%a{:href => "#"}
							%i.fa.fa-fw.fa-gear
							Notification #3
					%li.divider
					%li
						%a{:href => "#"}
							%i.fa.fa-fw.fa-power-off
							Log Out
		.collapse.navbar-collapse.navbar-ex1-collapse
			%ul.nav.navbar-nav.side-nav
				%li
					%a{"data-target" => "#demo", "data-toggle" => "collapse", :href => "javascript:;"}
						-if current_user.first_name || current_user.last_name
							=current_user.first_name + " " + current_user.last_name
							%i.fa.fa-fw.fa-caret-down
						-else
							=current_user.email
							%i.fa.fa-fw.fa-caret-down
					%ul#demo.collapse
						-# %li
						-# 	=link_to "Profile", user_path(@user) if user_signed_in?
						%li
							=link_to "Account", edit_user_registration_path
						%li.logout
							=link_to "Logout", destroy_user_session_path, method: :delete

				%li{class:"#{'active' if current_page?(dashboard_path)}"}
					=link_to dashboard_path do
						%i.fa.fa-fw.fa-dashboard
						Dashboard
				%li{class:"#{'active' if current_page?(invoices_path)}"}
					=link_to invoices_path do
						%i.fa.fa-edit
						Invoices
				%li{class:"#{'active' if current_page?(clients_path)}"}
					=link_to clients_path do
						%i.fa.fa-user
						Clients

app/views/dashboard/index.html.haml
#wrapper
	#page-wrapper
		.col-lg-12
			-if current_user.first_name.blank?
				=link_to "Add your details", edit_user_registration_path, class:"btn btn-primary add-details"
			.panel.panel-default
				.panel-heading
					%h2.clients-heading Invoices
				.panel-body
					=column_chart @clients.map{|client| {name: client.company_name, data: client.invoices.group_by_month(:created_at).maximum(:total)}}, legend: false
		
			.panel.panel-default
				.panel-heading
					%h2.clients-heading Latest invoices for #{Date.today.strftime("%B, %Y")}
				.panel-body
					-@clients.each do |client|
						-if client.invoices.count > 0
							.col-md-2
								%h5 #{client.company_name} for #{Date.today.strftime("%B, %Y")}
								=pie_chart client.invoices.group_by_day(:created_at).sum(:total), donut: true

app/views/homepage/index.html.haml
%nav#mainNav.navbar.navbar-default.navbar-fixed-top.navbar-custom
	.container
		/ Brand and toggle get grouped for better mobile display
		.navbar-header.page-scroll
			%button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle navigation
				Menu
				%i.fa.fa-bars
			%a.navbar-brand{:href => "#page-top"} Invoice.ME
		/ Collect the nav links, forms, and other content for toggling
		#bs-example-navbar-collapse-1.collapse.navbar-collapse
			%ul.nav.navbar-nav.navbar-right
				%li
					=link_to "Login", new_user_session_path, class:"btn btn-success"
				%li
					=link_to "Signup", new_user_registration_path, class:"btn btn-outline btn-sm"
%header
	.container
		.row
			.col-lg-12
				.fa.fa-clock-o.fa-5x
				.intro-text
					%span.name Invoice.me
					-# %hr.star-light/
					%span.skills Invoice application for small businesses.
				

/ About Section
%section#about.success
	.container
		.row
			.col-lg-12.text-center
				%h2 About
				%hr.star-primary/
		.row
			.col-lg-4.col-lg-offset-2
				%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim culpa ducimus numquam, maiores nulla quisquam vitae ad labore vel, laudantium expedita quas fugiat mollitia! Suscipit, sunt quidem eos animi non?
			.col-lg-4
				%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius eos voluptates minima, repellendus distinctio aliquam incidunt quas voluptatem esse aliquid modi, non aspernatur, fuga nobis eligendi labore inventore! Explicabo, inventore.
			.col-lg-8.col-lg-offset-2.text-center
				%a.btn.btn-lg.btn-outline{:href => "#"}
					%i.fa.fa-download
					Magic button

/ Footer
%footer.text-center
	.footer-below
		.container
			.row
				.col-lg-12
					Copyright © Drmrsan 2017

app/views/invoices/_form.html.haml
=simple_form_for @invoice do |f|
	
	=render 'shared/error_messages', obj: @invoice
	.row
		.col-md-6
			.form-inline.form-field
				=f.input :name, class:"form-control", label:false, input_html:{value:"INVOICE NAME"}
			=f.input :description, class:"form-control", label:false, placeholder:"Add description..."
		.col-md-4.col-md-offset-2
			=current_user.company_logo
	%hr/
	.row
		.col-md-12
			.form-inline
				=f.input :invoice_number, class:"form-control", label:"Invoice No.", input_html: {value: "#INV_"}
				=f.select(:currency, @currencies.xpath('//Ccy').map{|name| [name.text]}, {prompt:"Currency"}, {class:"currency-select"})
				
	%hr/
	.row
		.col-md-4
			%h5 From:
			%p=current_user.first_name + " " + current_user.last_name
			%p=current_user.address
			%p=current_user.postal_code + " " + current_user.city
			%p=current_user.country
			=link_to "Edit business profile", edit_user_registration_path, target:"_blank", class:"edit-bussines-profile"
			
			
		.col-md-4
			%h5 To:
			=collection_select(:invoice, :client_id, Client.all, :id, :company_name, {prompt:"Select Client"})
			=f.input :date, as: :string, class:"form-control", id:"invoice_date", placeholder:"Select Date"
			.dropdown.form-group
				=f.select(:invoice_due, @invoice_due_list.map{ |value| [value, value] },{prompt:"Payment method"}, class:"dropdown-toggle btn btn-default form-control")

	%hr/
	.row.items-header
		.col-md-3
			%h5 Item
		.col-md-3
			%h5 Price
		.col-md-3
			%h5 Qty
		.col-md-3
			%h5 Amount
	%hr/
	.row.col-md-12
		=f.simple_fields_for :items, input_html:{id:"invoice-items"} do |item|
			=render 'item_fields', f: item
		.links
			=link_to_add_association 'Add Item', f, :items, class:"btn btn-success"

	%hr/
	.row
		.col-md-6.col-md-offset-6
			.subtotal-cost
				%h5 Subtotal
				.input-group
					%span.input-group-addon
					=f.input_field :subtotal, class:"form-control subtotal", label:false, placeholder:"Subtotal"
				
				
				%hr/
			=f.input :tax, class:"form-control", label: "TAX (%)"
		
			.total-cost
				%h5 Total
				.input-group
					%span.input-group-addon
					=f.input_field :total, class:"form-control total", label:false, placeholder:"Total"
	%hr/
	.row
		.col-md-12
			=f.input :invoice_note, class:"form-control"
			=f.button :submit, class:"btn btn-success"
			=link_to "Cancel", invoices_path, class:"btn btn-default"

app/views/invoices/_item_fields.html.haml
.row.nested-fields
	.col-md-3.form-item
		=f.input_field :name, class:"form-control name",label: false, placeholder:"Item name & description"
	.col-md-2.form-item
		=f.input_field :rate, class:"form-control rate text-right",label: false, placeholder: "Rate / Price"
	.col-md-3.form-item
		=f.input_field :qty, class:"form-control qty text-right", label: false, placeholder: "Quantity"
	.col-md-3.form-item
		.input-group
			%span.input-group-addon
			=f.input_field :amount, class:"form-control amount text-right", label: false, placeholder:"Amount"
	.col-md-1.text-right
		=link_to_remove_association 'Remove', f, class:"btn btn-danger"

app/views/invoices/index.html.haml
#wrapper
	#page-wrapper
		.col-lg-12
			.panel.panel-default
				.panel-heading
					%h2.clients-heading Invoice section
					=link_to "New Invoice", new_invoice_path, class:"btn btn-success"
				.panel-body
					%table.table.table-striped.invoices.table-hover
						%thead
							%tr
								%th Client Name
								%th Invoice Name
								%th Invoice Number
								%th Currency
								%th Date
								%th Created At
								%th Invoice Due
								%th Invoice Note
								%th Details
						%tbody
							-@invoices.each do |invoice|
								%tr
									%td=invoice.client.company_name
									%td=invoice.name
									%td=invoice.invoice_number
									%td=invoice.currency
									%td=invoice.date.strftime("%d %B, %Y") if invoice.date
									%td=invoice.created_at.strftime("%d %B, %Y")
									%td=invoice.invoice_due
									%td=invoice.invoice_note
									%td=link_to "Details", invoice_path(invoice), class:"btn btn-default btn-sm"

:javascript
	$(document).ready(function(){
		$('.invoices').DataTable();
	});
	

app/views/invoices/invoice.pdf.haml
#wrapper
	#page-wrapper
		.col-lg-12
			.panel.panel-default
				.panel-heading
					.row
						.col-md-6
							%h2.clients-heading=current_user.company_name
							%p=current_user.address
							%p=current_user.postal_code + " " + current_user.city
							%p=current_user.country
						
						.col-md-6.text-right
							%h2 Invoice
							%p.invoice-date=@invoice.date.strftime("%d %B, %Y")

				.panel-body		
					.col-md-6
						%h4 To:
						%p=@invoice.client.first_name + " " + @invoice.client.last_name
						%p=@invoice.client.company_name
						%p=@invoice.client.address
						%p=@invoice.client.city + ", " + @invoice.client.postal_code
						%p=@invoice.client.phone
					.col-md-6
						%h4=@invoice.invoice_number
						%p Payment due: #{@invoice.invoice_due}
					
					.row
						.col-md-12
							%table.table.table-bordered.table-hover.table-striped
								%thead
									%tr
										%th Description
										%th Price
										%th Qty
										%th Amount
								%tbody
									-@invoice.items.each do |item|
										%tr
											%td=item.name if item.name
											%td=item.rate if item.rate
											%td=item.qty if item.qty
											%td #{item.amount} #{@invoice.currency}

							.col-md-4.col-md-offset-8.table-summary
								%table.table.table-bordered.table-hover
									%tbody
										%tr
											%th.text-center Subtotal
											%td.text-right #{@invoice.subtotal} #{@invoice.currency}
										%tr
											%th.text-center Tax
											%td.text-right #{@invoice.tax} #{"%"}
										%tr
											%th.text-center Total
											%td.text-right #{@invoice.total} #{@invoice.currency}

app/views/invoices/new.html.haml
#wrapper
	#page-wrapper
		.col-lg-12
			.panel.panel-default
				.panel-heading
					%h4.text-center New Invoice
				.panel-body
					=render 'invoices/form'
:javascript
	$(document).ready(function(){
		$('#invoice_date').datepicker({
			format: "dd MM, yyyy"
		});
	})
	

app/views/invoices/show.html.haml
#wrapper
	#page-wrapper
		.col-lg-12
			.panel.panel-default
				.panel-heading
					.row
						.col-md-6
							%h2.clients-heading=current_user.company_name
							%p=current_user.address
							%p=current_user.postal_code + " " + current_user.city
							%p=current_user.country
						
						.col-md-6.text-right
							%h2 Invoice
							%p.invoice-date=@invoice.date.strftime("%d %B, %Y")

				.panel-body		
					.col-md-6
						%h4 To:
						%p=@invoice.client.first_name + " " + @invoice.client.last_name
						%p=@invoice.client.company_name
						%p=@invoice.client.address
						%p=@invoice.client.city + ", " + @invoice.client.postal_code
						%p=@invoice.client.phone
					.col-md-6
						%h4=@invoice.invoice_number
						%p Payment due: #{@invoice.invoice_due}
					
					.row
						.col-md-12
							%table.table.table-bordered.table-hover.table-striped
								%thead
									%tr
										%th Description
										%th Price
										%th Qty
										%th Amount
								%tbody
									-@invoice.items.each do |item|
										%tr
											%td=item.name if item.name
											%td=item.rate if item.rate
											%td=item.qty if item.qty
											%td=item.amount if item.amount

							.col-md-4.col-md-offset-8.table-summary
								%table.table.table-bordered.table-hover
									%tbody
										%tr
											%th.text-center Subtotal
											%td.text-right #{@invoice.subtotal} #{@invoice.currency}
										%tr
											%th.text-center Tax
											%td.text-right #{@invoice.tax} #{"%"}
										%tr
											%th.text-center Total
											%td.text-right #{@invoice.total} #{@invoice.currency}
					=link_to "Print", "#", onclick:"printPage()", class:"btn btn-success"
					&nbsp
					=link_to "Save as PDF", "#", class:"btn btn-primary"

:javascript
	function printPage(){
		window.print();
	}

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title InvoicesApplication
		= csrf_meta_tags
		= stylesheet_link_tag		'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	%body{class:"#{'homepage' if @index}"}
		= render 'dashboard/navigation'
		.flash-message
			=render 'shared/messages'
		= yield

app/views/shared/_error_messages.html.haml
- if obj.errors.any?
  .error_explanation
    %h2
      = pluralize(obj.errors.count, "error")
      prevented this record from being saved:
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_messages.html.haml
-flash.each do |key, value|
	%div{class:"alert alert-#{key}"}
		=value

app/views/users/show.html.haml
#wrapper	
	#page-wrapper
		.container-fluid
			%h2 Account details
			.row
				.col-lg-12
					.panel
						=@user.email
						=link_to "Back to Dashboard", dashboard_path